//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengerCarCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteSheet
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public Nullable<int> PlannedProfit { get; set; }
        public int RealProfit { get; set; }
        public int DriverNumber { get; set; }
        public int RouteNumber { get; set; }
        public string BusNumber { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Route Route { get; set; }
    }
}
